name: Generate documentation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - uses: mattnotmitt/doxygen-action@v1
      with:
        working-directory: 'docs/'
        doxyfile-path: 'docs/Doxyfile'
